### ISSUE TITLE
AttributeError: 'SolverCbc' object has no attribute 'vars'

### ISSUE THREAD

**Issue by siddhajj** [coin-or/python-mip#14]
I recently updated the mip version from 1.3.15 to 1.4.3. I had a working code before I updated the package and when running the code with the updated package I get the following error:

Traceback (most recent call last):
  File "optimization.py", line 48, in <module>
    status = optimization("cbc")
  File "/home/xxxx/projects/xxxx/xxx/optimizer_helper.py", line 887, in optimization
    opt.objective += (coeff * my_var[i])
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/mip/model.py", line 942, in objective
    return self.solver.get_objective()
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/mip/cbc.py", line 409, in get_objective
    return xsum(obj[j]*self.vars[j] for j in range(self.num_cols())
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/mip/model.py", line 1944, in xsum
    for term in terms:
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/mip/cbc.py", line 410, in <genexpr>
    if abs(obj[j]) >= 1e-15)
AttributeError: 'SolverCbc' object has no attribute 'vars'

I can however access opt.vars explicitly and print the number of variables (which matches the number I was getting when the code was working correctly on version 1.3.15). Any idea what might be the issue?

**Comment by h-g-s** [comment]
Hmm, why are you querying the vars in the solver object ? I think that it is better to query vars in the Model object.

**Comment by siddhajj** [comment]
I am not querying the var. I am getting this error when modifying the objective function. "opt.objective += (coeff * my_var[i])"

**Comment by h-g-s** [comment]
Hmm, maybe it is because the operator += is not overloaded yet (only the =). I'll see it

**Comment by h-g-s** [comment]
This was fixed in the last versions.   Please check it.
